[package]
name = "masluna_core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
wasmer = { version = "6.1"}
# wasmer-compiler-llvm = "6.1"

async-fs = "2.2"


[lints]
workspace = true
