[package]
name = "masluna_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = [ "derive" ] }
masluna_core = { path = "../masluna_core" }

smol = "2.0"

[lints]
workspace = true
